// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkKH8RueeEtdrN1uYomedfAAU6IAhuRoI',
    appId: '1:42911666915:web:58c9604b3b3d8210df6bd6',
    messagingSenderId: '42911666915',
    projectId: 'fitbody-368404',
    authDomain: 'fitbody-368404.firebaseapp.com',
    databaseURL: 'https://fitbody-368404-default-rtdb.firebaseio.com',
    storageBucket: 'fitbody-368404.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0R4AvaGodhpWRtP2kWFqY-AfXJAovnSw',
    appId: '1:42911666915:android:29d0bfe69e4e0b27df6bd6',
    messagingSenderId: '42911666915',
    projectId: 'fitbody-368404',
    databaseURL: 'https://fitbody-368404-default-rtdb.firebaseio.com',
    storageBucket: 'fitbody-368404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeJ3t7EQaNLZxp2DkMqfzPspCrYqnjmNU',
    appId: '1:42911666915:ios:95bfdbe49c50e70ddf6bd6',
    messagingSenderId: '42911666915',
    projectId: 'fitbody-368404',
    databaseURL: 'https://fitbody-368404-default-rtdb.firebaseio.com',
    storageBucket: 'fitbody-368404.appspot.com',
    iosClientId: '42911666915-sqk2v0kl8fptngcie9ig1jaougg8hh0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeJ3t7EQaNLZxp2DkMqfzPspCrYqnjmNU',
    appId: '1:42911666915:ios:95bfdbe49c50e70ddf6bd6',
    messagingSenderId: '42911666915',
    projectId: 'fitbody-368404',
    databaseURL: 'https://fitbody-368404-default-rtdb.firebaseio.com',
    storageBucket: 'fitbody-368404.appspot.com',
    iosClientId: '42911666915-sqk2v0kl8fptngcie9ig1jaougg8hh0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
